name: Build and deploy Node.js app to Azure Web App - pawpal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install, build, and test
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm prune --production
          npm install
          npm run build --if-present
          # npm run test --if-present
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'pawpal'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BC9ABAE02DBF4764948CE5067C425599 }}
          package: .