name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run start:headless

      - name: Wait for server to start
        run: sleep 10   # Wartezeit entsprechend anpassen

      - name: Run tests
        run: npm test