name: Server and Jest Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: xvfb-run --auto-servernum npm start &

    - name: Wait for server to start
      run: sleep 5 # Anpassen der Wartezeit entsprechend Ihrer Anwendung

    - name: Run tests
      run: xvfb-run --auto-servernum npm test