name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start

      - name: Wait for server to start
        run: |
          timeout=$(($(date +%s) + 30))
          while ! curl -s http://localhost:3000 >/dev/null; do
            if [ "$(date +%s)" -gt "$timeout" ]; then
              echo "Server did not start within the timeout period."
              exit 1
            fi
            sleep 1
          done

      - name: Run Jest tests
        run: npm test

      - name: Stop server
        run: kill $(lsof -t -i:3000) || true